"""Shared helpers for the vLLM-Hook profiling harness.

Lifts the small utilities that already exist in
``Numerical_Analysis/benchmark_hidden_states.py`` (prompt synthesis, NVML
peek, env snapshot, CSV writer) and adds the per-cell metric assembly used
by every benchmark in ``profiling/``.

No vLLM imports here — those happen inside ``profile_one_run.py`` so this
module can be imported on a dev box that doesn't have vLLM installed (for
e.g. ``summarize.py`` post-processing).
"""
from __future__ import annotations

import csv
import json
import os
import shutil
import statistics
import tempfile
import time
import uuid
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HOOK_DIR = "/dev/shm/vllm_hook"
DEFAULT_PROFILE_DIR = "/tmp/vllm_hook_profile"


# ---------------------------------------------------------------------------
# Storage variants (lifted from Numerical_Analysis/benchmark_hidden_states.py)
# ---------------------------------------------------------------------------

STORAGE_VARIANTS = {
    "rpc":           {"env": {},                                                              "storage": "rpc",  "last_token_only": False},
    "disk-pt":       {"env": {},                                                              "storage": "disk", "last_token_only": False},
    "disk-pt-async": {"env": {"VLLM_HOOK_ASYNC_SAVE": "1"},                                   "storage": "disk", "last_token_only": False},
    "disk-st":       {"env": {"VLLM_HOOK_USE_SAFETENSORS": "1"},                              "storage": "disk", "last_token_only": False},
    "disk-st-async": {"env": {"VLLM_HOOK_USE_SAFETENSORS": "1", "VLLM_HOOK_ASYNC_SAVE": "1"}, "storage": "disk", "last_token_only": False},
    "shm":           {"env": {"VLLM_HOOK_USE_SHM": "1"},                                      "storage": "shm",  "last_token_only": True},
}


def apply_variant_env(variant_id: str) -> Dict[str, Optional[str]]:
    """Set the env vars for a storage variant; return a snapshot for restoration."""
    if variant_id not in STORAGE_VARIANTS:
        raise KeyError(f"Unknown storage variant: {variant_id!r}. "
                       f"Known: {sorted(STORAGE_VARIANTS)}")
    keys = ("VLLM_HOOK_USE_SAFETENSORS", "VLLM_HOOK_ASYNC_SAVE", "VLLM_HOOK_USE_SHM")
    snap = {k: os.environ.get(k) for k in keys}
    for k in keys:
        os.environ.pop(k, None)
    for k, v in STORAGE_VARIANTS[variant_id]["env"].items():
        os.environ[k] = v
    return snap


def restore_env(snap: Dict[str, Optional[str]]) -> None:
    for k, v in snap.items():
        if v is None:
            os.environ.pop(k, None)
        else:
            os.environ[k] = v


@contextmanager
def variant_env(variant_id: str):
    snap = apply_variant_env(variant_id)
    try:
        yield
    finally:
        restore_env(snap)


def read_env_flags() -> Dict[str, bool]:
    return {
        "use_shm":         os.environ.get("VLLM_HOOK_USE_SHM", "0") == "1",
        "use_safetensors": os.environ.get("VLLM_HOOK_USE_SAFETENSORS", "0") == "1",
        "use_async_save":  os.environ.get("VLLM_HOOK_ASYNC_SAVE", "0") == "1",
        "profile":         os.environ.get("VLLM_HOOK_PROFILE", "0") == "1",
    }


# ---------------------------------------------------------------------------
# Prompt synthesis (token-exact)
# ---------------------------------------------------------------------------

_SEED_TEXT = (
    "IBM is the largest industrial research organization in the world. "
    "IBM has 19 research facilities across a dozen countries. "
    "It held the record for most annual U.S. patents generated by a business. "
    "International Business Machines was incorporated in 1911 and renamed in 1924. "
)


def synth_prompts(target_tokens: int, tokenizer, n: int, jitter_pct: int = 0) -> List[str]:
    """Return ``n`` prompts of (approximately) ``target_tokens`` each.

    When ``jitter_pct > 0`` the per-prompt length is randomized in
    ``[target * (1 - p/100), target * (1 + p/100)]`` — useful for serve-path
    throughput tests where uniform prompt lengths defeat prefix caching.
    Uses a stable PRNG (seeded from ``target_tokens``) so cells are
    reproducible.
    """
    import random
    words_needed = int(target_tokens / 1.3) + 20
    repeated = (_SEED_TEXT * (words_needed // len(_SEED_TEXT.split()) + 4)).strip()

    if jitter_pct <= 0:
        ids = tokenizer.encode(repeated)[:target_tokens]
        prompt = tokenizer.decode(ids, skip_special_tokens=True)
        return [prompt] * n

    rng = random.Random(target_tokens)
    out: List[str] = []
    for _ in range(n):
        lo = max(8, int(target_tokens * (1 - jitter_pct / 100)))
        hi = max(lo + 1, int(target_tokens * (1 + jitter_pct / 100)))
        L = rng.randint(lo, hi)
        ids = tokenizer.encode(repeated)[:L]
        out.append(tokenizer.decode(ids, skip_special_tokens=True))
    return out


# ---------------------------------------------------------------------------
# NVML peek (cross-process GPU memory) + advanced per-rep memory snapshots
# ---------------------------------------------------------------------------


_NVML_HANDLE = None
_NVML_TRIED = False
_PSUTIL_PROC: Any = None
_PSUTIL_TRIED = False
_TORCH: Any = None
_TORCH_TRIED = False


def gpu_used_mb(gpu_index: int = 0) -> float:
    """Return system-wide GPU memory in use (MB) via NVML, or 0 on failure."""
    global _NVML_HANDLE, _NVML_TRIED
    if _NVML_HANDLE is None and not _NVML_TRIED:
        _NVML_TRIED = True
        try:
            import pynvml
            pynvml.nvmlInit()
            _NVML_HANDLE = pynvml.nvmlDeviceGetHandleByIndex(gpu_index)
        except Exception:
            _NVML_HANDLE = None
    if _NVML_HANDLE is None:
        return 0.0
    import pynvml
    info = pynvml.nvmlDeviceGetMemoryInfo(_NVML_HANDLE)
    return info.used / 1024 ** 2


def _maybe_torch():
    global _TORCH, _TORCH_TRIED
    if not _TORCH_TRIED:
        _TORCH_TRIED = True
        try:
            import torch
            _TORCH = torch
        except ImportError:
            _TORCH = None
    return _TORCH


def _maybe_psutil_proc():
    global _PSUTIL_PROC, _PSUTIL_TRIED
    if not _PSUTIL_TRIED:
        _PSUTIL_TRIED = True
        try:
            import psutil
            _PSUTIL_PROC = psutil.Process(os.getpid())
        except ImportError:
            _PSUTIL_PROC = None
    return _PSUTIL_PROC


def reset_cuda_peak_memory(gpu_index: int = 0) -> None:
    """Reset peak alloc/reserved stats on the given device so the next
    ``mem_snapshot()`` call observes the per-rep peak only.

    No-op when torch / CUDA / a CUDA context is not present in this process.
    """
    t = _maybe_torch()
    if t is None or not t.cuda.is_available() or not t.cuda.is_initialized():
        return
    try:
        t.cuda.reset_peak_memory_stats(gpu_index)
    except Exception:
        pass


def mem_snapshot(gpu_index: int = 0) -> Dict[str, float]:
    """Return a dict of per-process memory metrics (all in MB).

    Keys (always present; 0.0 when the source is unavailable):
      cuda_alloc_mb         — torch.cuda.memory_allocated()      (caching alloc)
      cuda_reserved_mb      — torch.cuda.memory_reserved()       (caching alloc)
      cuda_peak_alloc_mb    — torch.cuda.max_memory_allocated()  (since last reset)
      cuda_peak_reserved_mb — torch.cuda.max_memory_reserved()   (since last reset)
      host_rss_mb           — process RSS via psutil
      nvml_used_mb          — system-wide GPU mem (NVML)
    """
    out = {
        "cuda_alloc_mb":         0.0,
        "cuda_reserved_mb":      0.0,
        "cuda_peak_alloc_mb":    0.0,
        "cuda_peak_reserved_mb": 0.0,
        "host_rss_mb":           0.0,
        "nvml_used_mb":          0.0,
    }
    t = _maybe_torch()
    if t is not None and t.cuda.is_available() and t.cuda.is_initialized():
        try:
            out["cuda_alloc_mb"]         = t.cuda.memory_allocated(gpu_index)     / 1024 ** 2
            out["cuda_reserved_mb"]      = t.cuda.memory_reserved(gpu_index)      / 1024 ** 2
            out["cuda_peak_alloc_mb"]    = t.cuda.max_memory_allocated(gpu_index) / 1024 ** 2
            out["cuda_peak_reserved_mb"] = t.cuda.max_memory_reserved(gpu_index)  / 1024 ** 2
        except Exception:
            pass
    proc = _maybe_psutil_proc()
    if proc is not None:
        try:
            out["host_rss_mb"] = proc.memory_info().rss / 1024 ** 2
        except Exception:
            pass
    out["nvml_used_mb"] = gpu_used_mb(gpu_index)
    return out


# ---------------------------------------------------------------------------
# Artifact size helpers
# ---------------------------------------------------------------------------


def files_size_kb(paths: Iterable[str]) -> float:
    return sum(os.path.getsize(p) for p in paths if os.path.isfile(p)) / 1024.0


def dir_size_kb(path: str) -> float:
    total = 0
    for root, _dirs, files in os.walk(path):
        for f in files:
            try:
                total += os.path.getsize(os.path.join(root, f))
            except OSError:
                pass
    return total / 1024.0


def wait_for_artifact(hook_dir: str, run_id: str, *, use_safetensors: bool,
                      timeout_s: float = 10.0) -> bool:
    """Poll for the artifact under ``hook_dir/run_id``.

    Safetensors path: requires BOTH ``*.safetensors`` and ``*.json``.
    .pt path: any file under the run dir is sufficient.
    """
    import glob as _glob
    deadline = time.time() + timeout_s
    base = os.path.join(hook_dir, run_id)
    while time.time() < deadline:
        if use_safetensors:
            st = _glob.glob(os.path.join(base, "**", "*.safetensors"), recursive=True)
            js = _glob.glob(os.path.join(base, "**", "*.json"),         recursive=True)
            if st and js:
                return True
        else:
            if _glob.glob(os.path.join(base, "**", "*"), recursive=True):
                return True
        time.sleep(0.01)
    return False


# ---------------------------------------------------------------------------
# Profile snapshot helpers
# ---------------------------------------------------------------------------


def reset_profiler() -> None:
    """Reset PROF state between reps so each cell's snapshot is per-cell."""
    try:
        from vllm_hook_plugins._profiler import PROF, is_enabled
        if is_enabled():
            PROF.reset()
    except ImportError:
        pass


def profile_snapshot() -> Optional[Dict[str, Any]]:
    """Return the summary-only profile snapshot, or None if disabled."""
    try:
        from vllm_hook_plugins._profiler import PROF, is_enabled
        if is_enabled():
            return PROF.summary_only()
    except ImportError:
        pass
    return None


# ---------------------------------------------------------------------------
# Worker-side profile recovery
# ---------------------------------------------------------------------------
#
# Two sources for the worker's PROF snapshot:
#
#   1. Safetensors sidecar  — the .json that lives next to *.safetensors
#      under ``hook_dir/run_id/tp_rank_*/``. The worker embeds
#      ``meta["profile"] = PROF.summary_only()`` synchronously before the
#      generate() call returns, so this file exists by the time the driver
#      finishes a rep. Only present for storage variants that use safetensors
#      (``disk-st`` / ``disk-st-async``).
#
#   2. End-of-cell engine dump — the worker's atexit handler writes
#      ``profile-worker-<pid>-<seq>.json`` under VLLM_HOOK_PROFILE_DIR when
#      the EngineCore subprocess exits. Fires for *every* cell regardless
#      of storage variant, but only AFTER ``del engine`` triggers shutdown,
#      so the caller must wait a moment for the file to appear.
#
# Both functions return the snapshot in the same shape ``flatten_profile_into_row``
# expects (timers / counters / gauges) — driver and worker snapshots can be
# flattened into the same row with no collisions because driver timer names
# (hookllm.*, rpc.*, analyzer.*) are disjoint from worker names (hook.fire.*,
# worker.*, async.*). The only overlapping namespace is ``gauge.mem.*``,
# where the worker value overwrites the driver value — which is desirable
# because the worker has a real CUDA context and the driver doesn't.


def read_worker_sidecar_profile(hook_dir: str, run_id: str) -> Optional[Dict[str, Any]]:
    """Read the worker PROF snapshot embedded in a safetensors sidecar JSON.

    Looks under ``hook_dir/run_id/tp_rank_*/*.json`` for the most recent
    sidecar and returns its ``meta["profile"]`` field, or None if no sidecar
    is found (e.g. the cell used ``rpc`` or ``disk-pt`` storage).
    """
    base = os.path.join(hook_dir, run_id) if run_id else hook_dir
    if not run_id or not os.path.isdir(base):
        return None
    candidates: List[str] = []
    try:
        for tp_dir in os.listdir(base):
            tp_path = os.path.join(base, tp_dir)
            if not os.path.isdir(tp_path):
                continue
            for fn in os.listdir(tp_path):
                if fn.endswith(".json"):
                    candidates.append(os.path.join(tp_path, fn))
    except OSError:
        return None
    if not candidates:
        return None
    candidates.sort(key=lambda p: os.path.getmtime(p), reverse=True)
    try:
        with open(candidates[0]) as f:
            meta = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None
    return meta.get("profile")


def find_worker_engine_dump(profile_dir: Optional[str], since_ts: float,
                             *, timeout_s: float = 5.0) -> Optional[Dict[str, Any]]:
    """Poll for the worker's atexit profile dump.

    Returns the parsed snapshot dict from the freshest
    ``profile-worker-*.json`` under ``profile_dir`` with mtime > ``since_ts``,
    or None if nothing appears within ``timeout_s`` seconds. Polled at 200 ms
    cadence so we don't busy-loop.
    """
    if not profile_dir or not os.path.isdir(profile_dir):
        return None
    import glob as _glob
    pattern = os.path.join(profile_dir, "profile-worker-*.json")
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        fresh: List[tuple] = []
        for p in _glob.glob(pattern):
            try:
                m = os.path.getmtime(p)
            except OSError:
                continue
            if m > since_ts:
                fresh.append((p, m))
        if fresh:
            fresh.sort(key=lambda kv: kv[1], reverse=True)
            try:
                with open(fresh[0][0]) as f:
                    return json.load(f)
            except (OSError, json.JSONDecodeError):
                return None
        time.sleep(0.2)
    return None


# ---------------------------------------------------------------------------
# CSV / JSONL writers
# ---------------------------------------------------------------------------


def save_csv(rows: List[Dict[str, Any]], path: str) -> None:
    if not rows:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None
    # Union the keys across rows so we don't drop columns when an early row
    # lacks a metric a later row records.
    fieldnames: List[str] = []
    seen = set()
    for row in rows:
        for k in row:
            if k not in seen:
                seen.add(k)
                fieldnames.append(k)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def append_jsonl(record: Dict[str, Any], path: str) -> None:
    if os.path.dirname(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "a") as f:
        f.write(json.dumps(record, default=str))
        f.write("\n")


# ---------------------------------------------------------------------------
# Cell-context builder
# ---------------------------------------------------------------------------


def cell_context(**kwargs) -> Dict[str, Any]:
    """Standardize the per-cell context fields. Pass any of the §1.7 keys.

    Unspecified fields default to None — the union-keys CSV writer keeps the
    schema consistent across heterogeneous runs.
    """
    out: Dict[str, Any] = {
        "ts":                   time.strftime("%Y-%m-%d %H:%M:%S"),
        "model":                None,
        "dtype":                None,
        "tp_size":              None,
        "worker":               None,
        "analyzer":             None,
        "storage_variant":      None,
        "mode":                 None,             # last_token / all_tokens
        "hooks_on":             None,             # prefill / decode / both
        "prompt_len":           None,
        "max_tokens":           None,
        "batch_size":           None,
        "n_layers_captured":    None,
        "enable_prefix_caching": None,
        "enforce_eager":        None,
        "vllm_version":         None,
        "plugin_version":       None,
        "cuda_version":         None,
        "gpu_model":            None,
        "run_id":               None,
        "profile_tier":         1,
        "rep_idx":              0,
    }
    out.update(kwargs)
    return out


def summarize_samples(samples: Sequence[float]) -> Dict[str, float]:
    if not samples:
        return {"count": 0}
    n = len(samples)
    out = {
        "count": n,
        "mean":  sum(samples) / n,
        "min":   min(samples),
        "max":   max(samples),
    }
    if n > 1:
        out["std"] = statistics.stdev(samples)
        s = sorted(samples)
        out["p50"] = s[n // 2]
        out["p99"] = s[min(n - 1, int(n * 0.99))]
    return out


def flatten_profile_into_row(row: Dict[str, Any],
                              snap: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Flatten a profile snapshot into ``timer.<name>.<stat>`` columns."""
    if not snap:
        return row
    for tname, tstats in (snap.get("timers") or {}).items():
        for stat, val in tstats.items():
            row[f"timer.{tname}.{stat}"] = val
    for gname, gstats in (snap.get("gauges") or {}).items():
        for stat, val in gstats.items():
            row[f"gauge.{gname}.{stat}"] = val
    for cname, cval in (snap.get("counters") or {}).items():
        row[f"counter.{cname}"] = cval
    return row


# ---------------------------------------------------------------------------
# Run-dir cleanup
# ---------------------------------------------------------------------------


def clean_hook_dir(hook_dir: str) -> None:
    """Remove all run subdirectories under ``hook_dir`` (artifacts pile up
    quickly when sweeping many cells against tmpfs)."""
    if not hook_dir or not os.path.isdir(hook_dir):
        return
    for entry in os.listdir(hook_dir):
        full = os.path.join(hook_dir, entry)
        if os.path.isdir(full):
            shutil.rmtree(full, ignore_errors=True)
